eureka:
  client:
    register-with-eureka: false

server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: blog
          uri: http://web-service:8082
          predicates:
            - Path=/api/v1/blogs/**
        - id: characters
          uri: http://client-service:8083
          predicates:
            - Path=/api/v1/characters/**
        - id: users
          uri: http://web-service:8082
          predicates:
            - Path=/api/v1/users/**
  config:
    import: optional:configserver:http://config-server:8888
#  profiles:
#    default: dev

management:
  tracing:
    sampling:
      probability: 1.0

#---

#spring:
#  profiles:
#    active: dev
#  config:
#    import: optional:configserver:http://localhost:8888

#---

#spring:
#  profiles:
#    active: prod
#  config:
#    import: optional:configserver:http://config-server:8888
