version: '3.8'
services:
  app:
    build: .
    image: sogdev/webapi
    container_name: WebAPI
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: Redis
    command: --port 6380
    ports:
      - 6380:6380
