services:
  mongodb:
    container_name: mongo_db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=arma
      - MONGO_INITDB_ROOT_PASSWORD=arma
    volumes:
      - mongo:/data
    ports:
      - 27017:27017
    networks:
      - mongo
    restart: unless-stopped
  mongo-express:
    container_name: mongo_express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=arma
      - ME_CONFIG_MONGODB_ADMINPASSWORD=arma
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8081:8081
    networks:
      - mongo
    restart: unless-stopped
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - zipkin

networks:
  mongo:
    driver: bridge
  zipkin:
    driver: bridge

volumes:
  mongo: {}