eureka:
  client:
    register-with-eureka: false

server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: blog
          uri: http://web-service-1:8082
          predicates:
            - Path=/api/v1/blogs/**
        - id: characters
          uri: http://client-service-1:8083
          predicates:
            - Path=/api/v1/characters/**
        - id: users
          uri: http://web-service-1:8082
          predicates:
            - Path=/api/v1/users/**

management:
  tracing:
    sampling:
      probability: 1.0
