eureka:
  instance:
    hostname: discovery-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082
spring:
  application:
    name: web-service
  data:
    mongodb:
      username: arma
      password: arma
      host: localhost
      port: 27017
      database: webapp
      authentication-database: admin

application:
  config:
    characters-url: http://localhost:8080/api/v1/characters

management:
  tracing:
    sampling:
      probability: 1.0
